Repository fastcampus-final/go-together-be, pull requests merged in 2023-03, with the labels that each got.

#5 Fix coding convention
  src/main/java/com/example/gotogether/auth/controller/AuthController.java
  src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
  src/main/java/com/example/gotogether/auth/service/UserService.java
  src/main/java/com/example/gotogether/global/config/CustomAccessDeniedHandler.java
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
Labels: For: Backend

#7 Merge develop branch
  appspec.yml
  deploy.sh
  src/main/java/com/example/gotogether/admin/controller/AdminController.java
  src/main/java/com/example/gotogether/auth/controller/AuthController.java
  src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
  src/main/java/com/example/gotogether/auth/service/UserService.java
  src/main/java/com/example/gotogether/global/config/CustomAccessDeniedHandler.java
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
  src/main/java/com/example/gotogether/global/config/SwaggerConfig.java
  src/main/resources/application.properties
Labels: For: Backend, For: CI/CD

#8 feat: gradle files upload
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: For: CI/CD

#9 CI CD 변경 사항 적용
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: For: CI/CD

#11 ci cd 과정중 생긴 master commit 을 develop으로 최신화
  .github/workflows/main.yml
Labels: For: Backend

#12 feat: SignupDTO add passwordConfirmation
  src/main/java/com/example/gotogether/auth/dto/UserDTO.java
Labels: For: Backend, For: Frontend

#13 Develop
  src/main/java/com/example/gotogether/auth/dto/UserDTO.java
Labels: For: Backend, For: CI/CD

#14 Feat email duplication check
  src/main/java/com/example/gotogether/auth/controller/AuthController.java
  src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
  src/main/java/com/example/gotogether/auth/service/UserService.java
Labels: For: API, For: Backend, Priority: Low

#15 feat: server port 8080 -> 80
  src/main/resources/application.properties
Labels: For: Backend, For: CI/CD

#17 Develop
  .github/workflows/main.yml
  src/main/resources/application.properties
Labels: For: Backend

#20 Feat email check
  src/main/java/com/example/gotogether/GotogetherApplication.java
  src/main/java/com/example/gotogether/auth/controller/AuthController.java
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
Labels: For: Backend

#21 Develop
  src/main/java/com/example/gotogether/GotogetherApplication.java
  src/main/java/com/example/gotogether/auth/controller/AuthController.java
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
Labels: For: API, For: Backend

#19 Feat : entity 설계
  src/main/java/com/example/gotogether/GotogetherApplication.java
  src/main/java/com/example/gotogether/auth/entity/User.java
  src/main/java/com/example/gotogether/board/entity/Board.java
  src/main/java/com/example/gotogether/board/entity/Comment.java
  src/main/java/com/example/gotogether/cart/entity/Cart.java
  src/main/java/com/example/gotogether/category/entity/Category.java
  src/main/java/com/example/gotogether/page/entity/Banner.java
  src/main/java/com/example/gotogether/product/entity/Product.java
  src/main/java/com/example/gotogether/product/entity/ProductCategory.java
  src/main/java/com/example/gotogether/product/entity/ProductOption.java
  src/main/java/com/example/gotogether/product/entity/ProductStatus.java
  src/main/java/com/example/gotogether/reservation/entity/PaymentMethod.java
  src/main/java/com/example/gotogether/reservation/entity/Reservation.java
  src/main/java/com/example/gotogether/reservation/entity/ReservationDetail.java
  src/main/java/com/example/gotogether/reservation/entity/ReservationStatus.java
  src/main/java/com/example/gotogether/wishlist/entity/Wishlist.java
Labels: For: Backend

#43 Deploy 2022-03-23
  .github/workflows/main.yml
  src/main/java/com/example/gotogether/GotogetherApplication.java
  src/main/java/com/example/gotogether/auth/entity/User.java
  src/main/java/com/example/gotogether/board/entity/Board.java
  src/main/java/com/example/gotogether/board/entity/Comment.java
  src/main/java/com/example/gotogether/cart/entity/Cart.java
  src/main/java/com/example/gotogether/category/entity/Category.java
  src/main/java/com/example/gotogether/page/entity/Banner.java
  src/main/java/com/example/gotogether/product/entity/Product.java
  src/main/java/com/example/gotogether/product/entity/ProductCategory.java
  src/main/java/com/example/gotogether/product/entity/ProductOption.java
  src/main/java/com/example/gotogether/product/entity/ProductStatus.java
  src/main/java/com/example/gotogether/reservation/entity/PaymentMethod.java
  src/main/java/com/example/gotogether/reservation/entity/Reservation.java
  src/main/java/com/example/gotogether/reservation/entity/ReservationDetail.java
  src/main/java/com/example/gotogether/reservation/entity/ReservationStatus.java
  src/main/java/com/example/gotogether/wishlist/entity/Wishlist.java
  src/main/resources/application.properties
  src/main/resources/propertiesExample.text
Labels: For: CI/CD

#45 Deploy
  src/main/java/com/example/gotogether/auth/dto/UserDTO.java
Labels: For: CI/CD

#46 Feat image
  .gitignore
  build.gradle
  src/main/java/com/example/gotogether/global/aws/AwsS3Controller.java
  src/main/java/com/example/gotogether/global/aws/AwsS3Service.java
Labels: For: API, For: Backend, Priority: Low, Status: Review Needed, Type: Feature

#50 feat: 회원 정보 수정 구현
  build.gradle
  src/main/java/com/example/gotogether/auth/dto/UserDTO.java
  src/main/java/com/example/gotogether/auth/entity/User.java
  src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Type: Feature

#51 Feat categories
  src/main/java/com/example/gotogether/category/controller/AdminCategoryController.java
  src/main/java/com/example/gotogether/category/controller/CategoryController.java
  src/main/java/com/example/gotogether/category/dto/CategoryDTO.java
  src/main/java/com/example/gotogether/category/entity/Category.java
  src/main/java/com/example/gotogether/category/repository/CategoryRepository.java
  src/main/java/com/example/gotogether/category/service/CategoryService.java
  src/main/java/com/example/gotogether/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
Labels: For: Backend, Status: Completed

#52 Deploy 2022-03-23
  .gitignore
  build.gradle
  src/main/java/com/example/gotogether/admin/controller/AdminController.java
  src/main/java/com/example/gotogether/admin/service/AdminService.java
  src/main/java/com/example/gotogether/admin/service/impl/AdminServiceImpl.java
  src/main/java/com/example/gotogether/auth/controller/AuthController.java
  src/main/java/com/example/gotogether/auth/controller/TestController.java
  src/main/java/com/example/gotogether/auth/controller/UserController.java
  src/main/java/com/example/gotogether/auth/dto/MailDTO.java
  src/main/java/com/example/gotogether/auth/dto/TokenDTO.java
  src/main/java/com/example/gotogether/auth/dto/UserDTO.java
  src/main/java/com/example/gotogether/auth/entity/User.java
  src/main/java/com/example/gotogether/auth/exception/ErrorCode.java
  src/main/java/com/example/gotogether/auth/exception/UserException.java
  src/main/java/com/example/gotogether/auth/exception/UserExceptionType.java
  src/main/java/com/example/gotogether/auth/jwt/JwtExceptionFilter.java
  src/main/java/com/example/gotogether/auth/jwt/JwtProvider.java
  src/main/java/com/example/gotogether/auth/repository/UserRepository.java
  src/main/java/com/example/gotogether/auth/service/Impl/TokenServiceImpl.java
  src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
  src/main/java/com/example/gotogether/auth/service/TokenService.java
  src/main/java/com/example/gotogether/auth/service/UserService.java
  src/main/java/com/example/gotogether/category/controller/AdminCategoryController.java
  src/main/java/com/example/gotogether/category/controller/CategoryController.java
  src/main/java/com/example/gotogether/category/dto/CategoryDTO.java
  src/main/java/com/example/gotogether/category/entity/Category.java
  src/main/java/com/example/gotogether/category/repository/CategoryRepository.java
  src/main/java/com/example/gotogether/category/service/CategoryService.java
  src/main/java/com/example/gotogether/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/example/gotogether/global/aws/AwsS3Controller.java
  src/main/java/com/example/gotogether/global/aws/AwsS3Service.java
  src/main/java/com/example/gotogether/global/config/CustomAccessDeniedHandler.java
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
  src/main/java/com/example/gotogether/global/response/ResponseDTO.java
  src/main/java/com/example/gotogether/global/response/ResponseStatusCustomCode.java
Labels: For: Backend, For: CI/CD

#54 Feat: #35 Board 기능 구현
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/dto/BoardDTO.java
  src/main/java/com/example/gotogether/board/entity/Board.java
  src/main/java/com/example/gotogether/board/repository/BoardRepository.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Feature

#57 Feat: #35 Board 게시글 수정 기능 구현
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/dto/BoardDTO.java
  src/main/java/com/example/gotogether/board/entity/Board.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: In Progress, Type: Feature

#58 feat: 상품 추가 구현 (카테고리, 상품옵션 연동)
  src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
  src/main/java/com/example/gotogether/category/repository/CategoryRepository.java
  src/main/java/com/example/gotogether/product/controller/ProductController.java
  src/main/java/com/example/gotogether/product/controller/ProductOptionController.java
  src/main/java/com/example/gotogether/product/dto/ProductDTO.java
  src/main/java/com/example/gotogether/product/dto/ProductOptionDTO.java
  src/main/java/com/example/gotogether/product/entity/Product.java
  src/main/java/com/example/gotogether/product/entity/ProductCategory.java
  src/main/java/com/example/gotogether/product/entity/ProductOption.java
  src/main/java/com/example/gotogether/product/entity/ProductStatus.java
  src/main/java/com/example/gotogether/product/repository/ProductOptionRepository.java
  src/main/java/com/example/gotogether/product/repository/ProductRepository.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductOptionServiceImpl.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/gotogether/product/service/ProductOptionService.java
  src/main/java/com/example/gotogether/product/service/ProductService.java
Labels: For: API, For: Backend, Priority: Critical

#59 Feat 0325
  src/main/java/com/example/gotogether/auth/controller/AdminUserController.java
  src/main/java/com/example/gotogether/auth/dto/UserDTO.java
  src/main/java/com/example/gotogether/auth/entity/User.java
  src/main/java/com/example/gotogether/auth/service/AdminService.java
  src/main/java/com/example/gotogether/auth/service/Impl/AdminServiceImpl.java
  src/main/java/com/example/gotogether/board/dto/BoardDTO.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
  src/main/java/com/example/gotogether/category/dto/CategoryDTO.java
  src/main/java/com/example/gotogether/category/repository/CategoryRepository.java
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
  src/main/java/com/example/gotogether/product/controller/AdminProductController.java
  src/main/java/com/example/gotogether/product/controller/AdminProductOptionController.java
  src/main/java/com/example/gotogether/product/controller/ProductController.java
  src/main/java/com/example/gotogether/product/dto/ProductDTO.java
  src/main/java/com/example/gotogether/product/dto/ProductOptionDTO.java
  src/main/java/com/example/gotogether/product/entity/Product.java
  src/main/java/com/example/gotogether/product/entity/ProductCategory.java
  src/main/java/com/example/gotogether/product/entity/ProductOption.java
  src/main/java/com/example/gotogether/product/entity/ProductStatus.java
  src/main/java/com/example/gotogether/product/repository/ProductCategoryRepository.java
  src/main/java/com/example/gotogether/product/repository/ProductRepository.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/gotogether/product/service/ProductService.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Enhancement, Type: Feature

#60 Develop
  src/main/java/com/example/gotogether/auth/controller/AdminUserController.java
  src/main/java/com/example/gotogether/auth/dto/UserDTO.java
  src/main/java/com/example/gotogether/auth/entity/User.java
  src/main/java/com/example/gotogether/auth/service/AdminService.java
  src/main/java/com/example/gotogether/auth/service/Impl/AdminServiceImpl.java
  src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/dto/BoardDTO.java
  src/main/java/com/example/gotogether/board/entity/Board.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
  src/main/java/com/example/gotogether/category/dto/CategoryDTO.java
  src/main/java/com/example/gotogether/category/repository/CategoryRepository.java
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
  src/main/java/com/example/gotogether/product/controller/AdminProductController.java
  src/main/java/com/example/gotogether/product/controller/AdminProductOptionController.java
  src/main/java/com/example/gotogether/product/controller/ProductController.java
  src/main/java/com/example/gotogether/product/dto/ProductDTO.java
  src/main/java/com/example/gotogether/product/dto/ProductOptionDTO.java
  src/main/java/com/example/gotogether/product/entity/Product.java
  src/main/java/com/example/gotogether/product/entity/ProductCategory.java
  src/main/java/com/example/gotogether/product/entity/ProductOption.java
  src/main/java/com/example/gotogether/product/entity/ProductStatus.java
  src/main/java/com/example/gotogether/product/repository/ProductCategoryRepository.java
  src/main/java/com/example/gotogether/product/repository/ProductOptionRepository.java
  src/main/java/com/example/gotogether/product/repository/ProductRepository.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductOptionServiceImpl.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/gotogether/product/service/ProductOptionService.java
  src/main/java/com/example/gotogether/product/service/ProductService.java
Labels: For: API, For: Backend, For: CI/CD, Priority: High, Status: Completed, Type: Enhancement, Type: Feature

#61 Feat: #35 Board 게시글 권한 확인 기능 구현 및 게시글 수정 기능 수정
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Feature

#62 Feat: #35 Board 게시글 삭제 기능 구현
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Feature

#63 Feat: #35 Board 게시글 검색 기능 구현
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/repository/BoardRepository.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Feature

#64 feat: 검색 기능 임시 구현 (추후 refactoring 가능)
  src/main/java/com/example/gotogether/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
  src/main/java/com/example/gotogether/product/controller/ProductController.java
  src/main/java/com/example/gotogether/product/repository/ProductCategoryRepository.java
  src/main/java/com/example/gotogether/product/repository/ProductRepository.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/gotogether/product/service/ProductService.java
Labels: For: Backend

#65 Deploy
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/repository/BoardRepository.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
  src/main/java/com/example/gotogether/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
  src/main/java/com/example/gotogether/product/controller/ProductController.java
  src/main/java/com/example/gotogether/product/repository/ProductCategoryRepository.java
  src/main/java/com/example/gotogether/product/repository/ProductRepository.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/gotogether/product/service/ProductService.java
Labels: For: Backend, For: CI/CD

#67 Feat: #37 Admin-Reservation 예약 목록 조회
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
  src/main/java/com/example/gotogether/reservation/controller/AdminReservationController.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDTO.java
  src/main/java/com/example/gotogether/reservation/repository/ReservationRepository.java
  src/main/java/com/example/gotogether/reservation/service/ReservationService.java
  src/main/java/com/example/gotogether/reservation/service/impl/ReservationServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Feature

#69 feat: 상품관련 API 기능 구현
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
  src/main/java/com/example/gotogether/product/controller/AdminProductController.java
  src/main/java/com/example/gotogether/product/dto/ProductDTO.java
  src/main/java/com/example/gotogether/product/dto/ProductOptionDTO.java
  src/main/java/com/example/gotogether/product/entity/Product.java
  src/main/java/com/example/gotogether/product/entity/ProductOption.java
  src/main/java/com/example/gotogether/product/repository/ProductCategoryRepository.java
  src/main/java/com/example/gotogether/product/repository/ProductOptionRepository.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/gotogether/product/service/ProductService.java
Labels: For: API, For: Backend, Priority: High

#72 Feat 상품 옵션 CRUD 기능 구현
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
  src/main/java/com/example/gotogether/product/controller/AdminProductController.java
  src/main/java/com/example/gotogether/product/controller/AdminProductOptionController.java
  src/main/java/com/example/gotogether/product/controller/ProductController.java
  src/main/java/com/example/gotogether/product/dto/ProductDTO.java
  src/main/java/com/example/gotogether/product/dto/ProductOptionDTO.java
  src/main/java/com/example/gotogether/product/entity/ProductOption.java
  src/main/java/com/example/gotogether/product/repository/ProductOptionRepository.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductOptionServiceImpl.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/gotogether/product/service/ProductOptionService.java
Labels: For: API, For: Backend, Priority: High

#73 Feat : querydsl and several API
  build.gradle
  src/main/java/com/example/gotogether/auth/controller/AdminUserController.java
  src/main/java/com/example/gotogether/auth/controller/AuthController.java
  src/main/java/com/example/gotogether/auth/controller/UserController.java
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/category/controller/AdminCategoryController.java
  src/main/java/com/example/gotogether/category/controller/CategoryController.java
  src/main/java/com/example/gotogether/global/aws/AwsS3Controller.java
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
  src/main/java/com/example/gotogether/global/config/QuerydslConfiguration.java
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
  src/main/java/com/example/gotogether/page/controller/PageContentsAdminController.java
  src/main/java/com/example/gotogether/page/controller/PageContentsController.java
  src/main/java/com/example/gotogether/page/dto/RegionDTO.java
  src/main/java/com/example/gotogether/page/entity/Region.java
  src/main/java/com/example/gotogether/page/repository/RegionRepository.java
  src/main/java/com/example/gotogether/page/service/PageContentsService.java
  src/main/java/com/example/gotogether/page/service/impl/PageContentsServiceImpl.java
  src/main/java/com/example/gotogether/product/controller/ProductController.java
  src/main/java/com/example/gotogether/product/dto/ProductDTO.java
  src/main/java/com/example/gotogether/product/entity/Product.java
  src/main/java/com/example/gotogether/product/repository/ProductRepository.java
  src/main/java/com/example/gotogether/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/gotogether/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/gotogether/product/service/ProductService.java
  src/main/java/com/example/gotogether/reservation/controller/AdminReservationController.java
Labels: For: API, For: Backend, Priority: High, Status: Completed, Type: Enhancement, Type: Feature

#76 Feat details
  src/main/java/com/example/gotogether/category/controller/CategoryController.java
  src/main/java/com/example/gotogether/category/service/CategoryService.java
  src/main/java/com/example/gotogether/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
  src/main/java/com/example/gotogether/page/controller/PageContentsAdminController.java
  src/main/java/com/example/gotogether/page/service/PageContentsService.java
  src/main/java/com/example/gotogether/page/service/impl/PageContentsServiceImpl.java
Labels: For: API

#80 Deploy
  build.gradle
  src/main/java/com/example/gotogether/auth/controller/AdminUserController.java
  src/main/java/com/example/gotogether/auth/controller/AuthController.java
  src/main/java/com/example/gotogether/auth/controller/UserController.java
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
  src/main/java/com/example/gotogether/category/controller/AdminCategoryController.java
  src/main/java/com/example/gotogether/category/controller/CategoryController.java
  src/main/java/com/example/gotogether/category/service/CategoryService.java
  src/main/java/com/example/gotogether/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/example/gotogether/global/aws/AwsS3Controller.java
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
  src/main/java/com/example/gotogether/global/config/QuerydslConfiguration.java
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
  src/main/java/com/example/gotogether/page/controller/PageContentsAdminController.java
  src/main/java/com/example/gotogether/page/controller/PageContentsController.java
  src/main/java/com/example/gotogether/page/dto/RegionDTO.java
  src/main/java/com/example/gotogether/page/entity/Region.java
  src/main/java/com/example/gotogether/page/repository/RegionRepository.java
  src/main/java/com/example/gotogether/page/service/PageContentsService.java
  src/main/java/com/example/gotogether/page/service/impl/PageContentsServiceImpl.java
  src/main/java/com/example/gotogether/product/controller/AdminProductController.java
  src/main/java/com/example/gotogether/product/controller/AdminProductOptionController.java
  src/main/java/com/example/gotogether/product/controller/ProductController.java
  src/main/java/com/example/gotogether/product/dto/ProductDTO.java
  src/main/java/com/example/gotogether/product/dto/ProductOptionDTO.java
  src/main/java/com/example/gotogether/product/entity/Product.java
  src/main/java/com/example/gotogether/product/entity/ProductOption.java
  src/main/java/com/example/gotogether/product/repository/ProductCategoryRepository.java
  src/main/java/com/example/gotogether/product/repository/ProductOptionRepository.java
  src/main/java/com/example/gotogether/product/repository/ProductRepository.java
  src/main/java/com/example/gotogether/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/gotogether/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductOptionServiceImpl.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/gotogether/product/service/ProductOptionService.java
  src/main/java/com/example/gotogether/product/service/ProductService.java
  src/main/java/com/example/gotogether/reservation/controller/AdminReservationController.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDTO.java
  src/main/java/com/example/gotogether/reservation/entity/Reservation.java
  src/main/java/com/example/gotogether/reservation/entity/ReservationStatus.java
  src/main/java/com/example/gotogether/reservation/repository/ReservationRepository.java
  src/main/java/com/example/gotogether/reservation/service/ReservationService.java
  src/main/java/com/example/gotogether/reservation/service/impl/ReservationServiceImpl.java
Labels: For: CI/CD

#83 Feat: #32 User-Reservation 회원 예약 목록 조회 기능 구현
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
  src/main/java/com/example/gotogether/reservation/controller/AdminReservationController.java
  src/main/java/com/example/gotogether/reservation/controller/ReservationController.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDTO.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDetailDTO.java
  src/main/java/com/example/gotogether/reservation/repository/ReservationRepository.java
  src/main/java/com/example/gotogether/reservation/service/ReservationService.java
  src/main/java/com/example/gotogether/reservation/service/impl/ReservationServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Feature

#84 Feat: #32 User-Reservation 예약 상세 정보 조회 기능 구현
  src/main/java/com/example/gotogether/reservation/controller/ReservationController.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDTO.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDetailDTO.java
  src/main/java/com/example/gotogether/reservation/service/ReservationService.java
  src/main/java/com/example/gotogether/reservation/service/impl/ReservationServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Feature

#86 Feat: #32 User-Reservation 회원 예약 취소 기능 구현
  src/main/java/com/example/gotogether/reservation/controller/ReservationController.java
  src/main/java/com/example/gotogether/reservation/service/ReservationService.java
  src/main/java/com/example/gotogether/reservation/service/impl/ReservationServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Feature

#88 Feat: #32 User-Reservation 회원 예약 추가 기능 구현 및 회원 예약상태 수정 기능 리팩토링
  src/main/java/com/example/gotogether/reservation/controller/AdminReservationController.java
  src/main/java/com/example/gotogether/reservation/controller/ReservationController.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDTO.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDetailDTO.java
  src/main/java/com/example/gotogether/reservation/entity/Reservation.java
  src/main/java/com/example/gotogether/reservation/entity/ReservationDetail.java
  src/main/java/com/example/gotogether/reservation/entity/ReservationStatus.java
  src/main/java/com/example/gotogether/reservation/repository/ReservationDetailRepository.java
  src/main/java/com/example/gotogether/reservation/service/ReservationService.java
  src/main/java/com/example/gotogether/reservation/service/impl/ReservationServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Feature

#90 Feat: #78 Board 게시글 목록 조회
  src/main/java/com/example/gotogether/board/config/BoardTypeRequestConverter.java
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/dto/BoardDTO.java
  src/main/java/com/example/gotogether/board/entity/Board.java
  src/main/java/com/example/gotogether/board/entity/BoardType.java
  src/main/java/com/example/gotogether/board/repository/BoardRepository.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
  src/main/java/com/example/gotogether/global/config/WebConfig.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Feature

#91 Feat: #78 Board 게시글 상세 정보 조회 기능 구현
  src/main/java/com/example/gotogether/board/dto/BoardDTO.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Feature

#96 Feat: 관련상품 리스트
  src/main/java/com/example/gotogether/cart/controller/CartController.java
  src/main/java/com/example/gotogether/cart/dto/CartDTO.java
  src/main/java/com/example/gotogether/cart/entity/Cart.java
  src/main/java/com/example/gotogether/cart/repository/CartRepository.java
  src/main/java/com/example/gotogether/cart/service/CartService.java
  src/main/java/com/example/gotogether/cart/service/Impl/CartServiceImpl.java
  src/main/java/com/example/gotogether/product/controller/ProductController.java
  src/main/java/com/example/gotogether/product/entity/ProductOption.java
  src/main/java/com/example/gotogether/product/repository/ProductRepository.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/gotogether/product/service/ProductService.java
  src/main/java/com/example/gotogether/wishlist/controller/WishlistController.java
  src/main/java/com/example/gotogether/wishlist/dto/WishlistDTO.java
  src/main/java/com/example/gotogether/wishlist/entity/Wishlist.java
  src/main/java/com/example/gotogether/wishlist/repository/WishlistRepository.java
  src/main/java/com/example/gotogether/wishlist/service/Impl/WishlistServiceImpl.java
  src/main/java/com/example/gotogether/wishlist/service/WishlistService.java
Labels: For: API, Priority: Low

#92 Feat: Banner CRUD
  src/main/java/com/example/gotogether/page/controller/PageContentsAdminController.java
  src/main/java/com/example/gotogether/page/controller/PageContentsController.java
  src/main/java/com/example/gotogether/page/dto/BannerDTO.java
  src/main/java/com/example/gotogether/page/entity/Banner.java
  src/main/java/com/example/gotogether/page/repository/BannerRepository.java
  src/main/java/com/example/gotogether/page/service/BannerService.java
  src/main/java/com/example/gotogether/page/service/impl/BannerServiceImpl.java
Labels: For: API, For: Backend, Priority: Low, Type: Feature

#95 Feat: #78 Board 게시글 수정 기능 구현
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/dto/BoardDTO.java
  src/main/java/com/example/gotogether/board/entity/Board.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Feature

#98 develop branch Synchronize
  src/main/java/com/example/gotogether/product/controller/ProductController.java
  src/main/java/com/example/gotogether/product/repository/ProductRepository.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/gotogether/product/service/ProductService.java
Labels: For: CI/CD

#87 Feat: User 엔티티 수정
  src/main/java/com/example/gotogether/auth/controller/AdminUserController.java
  src/main/java/com/example/gotogether/auth/controller/AuthController.java
  src/main/java/com/example/gotogether/auth/dto/UserDTO.java
  src/main/java/com/example/gotogether/auth/entity/User.java
  src/main/java/com/example/gotogether/product/controller/AdminProductController.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
Labels: For: API, For: Backend, For: DB

#97 Feat: #78 Board 게시글 삭제 및 권한 확인 기능 구현
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Feature

#94 Feat grouping
  src/main/java/com/example/gotogether/auth/controller/AdminUserController.java
  src/main/java/com/example/gotogether/auth/controller/UserController.java
  src/main/java/com/example/gotogether/auth/dto/GroupDTO.java
  src/main/java/com/example/gotogether/auth/dto/UserDTO.java
  src/main/java/com/example/gotogether/auth/entity/Grouping.java
  src/main/java/com/example/gotogether/auth/entity/User.java
  src/main/java/com/example/gotogether/auth/repository/GroupingRepository.java
  src/main/java/com/example/gotogether/auth/service/AdminService.java
  src/main/java/com/example/gotogether/auth/service/Impl/AdminServiceImpl.java
  src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
  src/main/java/com/example/gotogether/page/controller/PageContentsController.java
  src/main/java/com/example/gotogether/page/service/PageContentsService.java
  src/main/java/com/example/gotogether/page/service/impl/PageContentsServiceImpl.java
  src/main/java/com/example/gotogether/product/repository/ProductCategoryRepository.java
  src/main/java/com/example/gotogether/product/repository/ProductRepository.java
  src/main/java/com/example/gotogether/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/gotogether/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
Labels: For: API, For: Backend, For: CLI, Priority: High, Status: Review Needed, Type: Enhancement, Type: Feature

#99 Develop
  src/main/java/com/example/gotogether/auth/controller/AdminUserController.java
  src/main/java/com/example/gotogether/auth/controller/AuthController.java
  src/main/java/com/example/gotogether/auth/controller/UserController.java
  src/main/java/com/example/gotogether/auth/dto/GroupDTO.java
  src/main/java/com/example/gotogether/auth/dto/UserDTO.java
  src/main/java/com/example/gotogether/auth/entity/Grouping.java
  src/main/java/com/example/gotogether/auth/entity/User.java
  src/main/java/com/example/gotogether/auth/repository/GroupingRepository.java
  src/main/java/com/example/gotogether/auth/service/AdminService.java
  src/main/java/com/example/gotogether/auth/service/Impl/AdminServiceImpl.java
  src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
  src/main/java/com/example/gotogether/board/config/BoardTypeRequestConverter.java
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/dto/BoardDTO.java
  src/main/java/com/example/gotogether/board/entity/Board.java
  src/main/java/com/example/gotogether/board/entity/BoardType.java
  src/main/java/com/example/gotogether/board/repository/BoardRepository.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
  src/main/java/com/example/gotogether/global/config/WebConfig.java
  src/main/java/com/example/gotogether/page/controller/PageContentsAdminController.java
  src/main/java/com/example/gotogether/page/controller/PageContentsController.java
  src/main/java/com/example/gotogether/page/dto/BannerDTO.java
  src/main/java/com/example/gotogether/page/entity/Banner.java
  src/main/java/com/example/gotogether/page/repository/BannerRepository.java
  src/main/java/com/example/gotogether/page/service/BannerService.java
  src/main/java/com/example/gotogether/page/service/PageContentsService.java
  src/main/java/com/example/gotogether/page/service/impl/BannerServiceImpl.java
  src/main/java/com/example/gotogether/page/service/impl/PageContentsServiceImpl.java
  src/main/java/com/example/gotogether/product/controller/AdminProductController.java
  src/main/java/com/example/gotogether/product/repository/ProductCategoryRepository.java
  src/main/java/com/example/gotogether/product/repository/ProductRepository.java
  src/main/java/com/example/gotogether/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/gotogether/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/gotogether/reservation/controller/AdminReservationController.java
  src/main/java/com/example/gotogether/reservation/controller/ReservationController.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDTO.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDetailDTO.java
  src/main/java/com/example/gotogether/reservation/entity/Reservation.java
  src/main/java/com/example/gotogether/reservation/entity/ReservationDetail.java
  src/main/java/com/example/gotogether/reservation/entity/ReservationStatus.java
  src/main/java/com/example/gotogether/reservation/repository/ReservationDetailRepository.java
  src/main/java/com/example/gotogether/reservation/repository/ReservationRepository.java
  src/main/java/com/example/gotogether/reservation/service/ReservationService.java
  src/main/java/com/example/gotogether/reservation/service/impl/ReservationServiceImpl.java
Labels: For: CI/CD
