Repository fastcampus-final/go-together-be, pull requests merged in 2023-04, with the labels that each got.

#101 Feat: #78 Board 게시글 검색 기능 구현
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/repository/BoardRepository.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Feature

#103 Feat: #78 Board 회원 여행후기 목록 조회 기능 구현
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/dto/BoardDTO.java
  src/main/java/com/example/gotogether/board/repository/BoardRepository.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Feature

#111 Refactor: URL ect
  src/main/java/com/example/gotogether/auth/controller/AdminUserController.java
  src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
  src/main/java/com/example/gotogether/cart/controller/CartController.java
  src/main/java/com/example/gotogether/cart/service/Impl/CartServiceImpl.java
  src/main/java/com/example/gotogether/product/controller/AdminProductController.java
  src/main/java/com/example/gotogether/product/controller/ProductController.java
  src/main/java/com/example/gotogether/wishlist/controller/WishlistController.java
Labels: For: API, Priority: Low

#107 Refactor: Reservation 회원 예약 추가 및 회원 예약 취소 리팩토링
  src/main/java/com/example/gotogether/board/entity/BoardType.java
  src/main/java/com/example/gotogether/product/entity/ProductOption.java
  src/main/java/com/example/gotogether/reservation/controller/ReservationController.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDTO.java
  src/main/java/com/example/gotogether/reservation/entity/PaymentMethod.java
  src/main/java/com/example/gotogether/reservation/entity/Reservation.java
  src/main/java/com/example/gotogether/reservation/entity/ReservationStatus.java
  src/main/java/com/example/gotogether/reservation/service/impl/ReservationServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Enhancement

#113 Refactor: Reservation 회원 예약 취소 및 예약 상태 수정 리팩토링
  src/main/java/com/example/gotogether/reservation/controller/AdminReservationController.java
  src/main/java/com/example/gotogether/reservation/controller/ReservationController.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDTO.java
  src/main/java/com/example/gotogether/reservation/entity/Reservation.java
  src/main/java/com/example/gotogether/reservation/entity/ReservationDetail.java
  src/main/java/com/example/gotogether/reservation/entity/ReservationStatus.java
  src/main/java/com/example/gotogether/reservation/service/impl/ReservationServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Enhancement

#114 Refactor: Reservation 전체 예약 목록 조회 및 예약 상세 정보 조회 리팩토링
  src/main/java/com/example/gotogether/reservation/controller/AdminReservationController.java
  src/main/java/com/example/gotogether/reservation/controller/ReservationController.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDTO.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDetailDTO.java
  src/main/java/com/example/gotogether/reservation/service/ReservationService.java
  src/main/java/com/example/gotogether/reservation/service/impl/ReservationServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Enhancement

#116 Deploy
  src/main/java/com/example/gotogether/auth/controller/AdminUserController.java
  src/main/java/com/example/gotogether/auth/dto/UserDTO.java
  src/main/java/com/example/gotogether/auth/service/Impl/AdminServiceImpl.java
  src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/dto/BoardDTO.java
  src/main/java/com/example/gotogether/board/entity/BoardType.java
  src/main/java/com/example/gotogether/board/repository/BoardRepository.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
  src/main/java/com/example/gotogether/cart/controller/CartController.java
  src/main/java/com/example/gotogether/cart/service/Impl/CartServiceImpl.java
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
  src/main/java/com/example/gotogether/product/controller/AdminProductController.java
  src/main/java/com/example/gotogether/product/controller/ProductController.java
  src/main/java/com/example/gotogether/product/dto/ProductDTO.java
  src/main/java/com/example/gotogether/product/dto/ProductOptionDTO.java
  src/main/java/com/example/gotogether/product/entity/ProductOption.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/gotogether/reservation/controller/AdminReservationController.java
  src/main/java/com/example/gotogether/reservation/controller/ReservationController.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDTO.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDetailDTO.java
  src/main/java/com/example/gotogether/reservation/entity/PaymentMethod.java
  src/main/java/com/example/gotogether/reservation/entity/Reservation.java
  src/main/java/com/example/gotogether/reservation/entity/ReservationDetail.java
  src/main/java/com/example/gotogether/reservation/entity/ReservationStatus.java
  src/main/java/com/example/gotogether/reservation/service/ReservationService.java
  src/main/java/com/example/gotogether/reservation/service/impl/ReservationServiceImpl.java
  src/main/java/com/example/gotogether/wishlist/controller/WishlistController.java
Labels: For: CI/CD

#120 Refactor: Reservation 회원 예약 목록 조회 리팩토링
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
  src/main/java/com/example/gotogether/product/repository/ProductRepository.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/gotogether/reservation/controller/ReservationController.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDTO.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDetailDTO.java
  src/main/java/com/example/gotogether/reservation/repository/ReservationDetailRepository.java
  src/main/java/com/example/gotogether/reservation/repository/ReservationDetailRepositoryCustom.java
  src/main/java/com/example/gotogether/reservation/repository/ReservationDetailRepositoryImpl.java
  src/main/java/com/example/gotogether/reservation/repository/ReservationRepository.java
  src/main/java/com/example/gotogether/reservation/service/ReservationService.java
  src/main/java/com/example/gotogether/reservation/service/impl/ReservationServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Enhancement

#121 Deploy
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
  src/main/java/com/example/gotogether/product/repository/ProductRepository.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/gotogether/reservation/controller/ReservationController.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDTO.java
  src/main/java/com/example/gotogether/reservation/dto/ReservationDetailDTO.java
  src/main/java/com/example/gotogether/reservation/repository/ReservationDetailRepository.java
  src/main/java/com/example/gotogether/reservation/repository/ReservationDetailRepositoryCustom.java
  src/main/java/com/example/gotogether/reservation/repository/ReservationDetailRepositoryImpl.java
  src/main/java/com/example/gotogether/reservation/repository/ReservationRepository.java
  src/main/java/com/example/gotogether/reservation/service/ReservationService.java
  src/main/java/com/example/gotogether/reservation/service/impl/ReservationServiceImpl.java
Labels: For: CI/CD

#133 Feat 0407
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
  src/main/java/com/example/gotogether/product/controller/ProductController.java
  src/main/java/com/example/gotogether/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/gotogether/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/gotogether/product/service/ProductService.java
Labels: For: Backend, Priority: High, Status: Completed, Type: Enhancement, Type: Feature

#134 Deploy
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
  src/main/java/com/example/gotogether/product/controller/ProductController.java
  src/main/java/com/example/gotogether/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/gotogether/product/repository/ProductRepositoryCustomImpl.java
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/gotogether/product/service/ProductService.java
Labels: For: CI/CD

#136 Refactor: Board 게시글 API 관련 리팩토링
  README.md
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Enhancement

#137 Deploy
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
  src/main/java/com/example/gotogether/global/config/SecurityConfig.java
Labels: For: CI/CD

#138 Feat 0409 front
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
  src/main/java/com/example/gotogether/wishlist/dto/WishlistDTO.java
Labels: For: CI/CD

#139 Develop
  src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
  src/main/java/com/example/gotogether/wishlist/dto/WishlistDTO.java
Labels: For: CI/CD

#140 fix: 위시리스트 예외처리 변경
  src/main/java/com/example/gotogether/wishlist/controller/WishlistController.java
  src/main/java/com/example/gotogether/wishlist/service/Impl/WishlistServiceImpl.java
Labels: For: CI/CD

#141 Deploy
  src/main/java/com/example/gotogether/wishlist/controller/WishlistController.java
  src/main/java/com/example/gotogether/wishlist/service/Impl/WishlistServiceImpl.java
Labels: For: CI/CD

#142 Refactor: Board 게시글 전반적인 리팩토링
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/dto/BoardDTO.java
  src/main/java/com/example/gotogether/board/entity/Board.java
  src/main/java/com/example/gotogether/board/entity/BoardType.java
  src/main/java/com/example/gotogether/board/entity/Comment.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
Labels: For: API, For: Backend, Priority: Low, Status: Completed, Type: Enhancement

#143 Deploy
  src/main/java/com/example/gotogether/board/controller/BoardController.java
  src/main/java/com/example/gotogether/board/dto/BoardDTO.java
  src/main/java/com/example/gotogether/board/entity/Board.java
  src/main/java/com/example/gotogether/board/entity/BoardType.java
  src/main/java/com/example/gotogether/board/entity/Comment.java
  src/main/java/com/example/gotogether/board/service/BoardService.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
Labels: For: CI/CD

#145 Deploy
  src/main/java/com/example/gotogether/wishlist/controller/WishlistController.java
  src/main/java/com/example/gotogether/wishlist/service/Impl/WishlistServiceImpl.java
  src/main/java/com/example/gotogether/wishlist/service/WishlistService.java
Labels: For: CI/CD

#146 Feat 0410 cart
  src/main/java/com/example/gotogether/cart/dto/CartDTO.java
  src/main/java/com/example/gotogether/cart/service/Impl/CartServiceImpl.java
  src/main/java/com/example/gotogether/product/dto/ProductOptionDTO.java
Labels: For: CI/CD

#147 Deploy
  src/main/java/com/example/gotogether/cart/dto/CartDTO.java
  src/main/java/com/example/gotogether/cart/service/Impl/CartServiceImpl.java
  src/main/java/com/example/gotogether/product/dto/ProductOptionDTO.java
Labels: For: CI/CD

#150 feat: 장바구니 출력값 변경
  src/main/java/com/example/gotogether/cart/dto/CartDTO.java
Labels: For: Backend

#151 Deploy
  src/main/java/com/example/gotogether/cart/dto/CartDTO.java
Labels: For: CI/CD

#152 feat: 개발 테스트용 API 삭제
  src/main/java/com/example/gotogether/auth/controller/TestController.java
Labels: For: CI/CD

#153 Develop
  src/main/java/com/example/gotogether/auth/controller/TestController.java
Labels: For: CI/CD

#155 Refactor: Reservation 회원 예약 추가 기능 리팩토링
  src/main/java/com/example/gotogether/cart/repository/CartRepository.java
  src/main/java/com/example/gotogether/reservation/controller/ReservationController.java
  src/main/java/com/example/gotogether/reservation/service/impl/ReservationServiceImpl.java
Labels: For: API, For: Backend, Priority: Medium, Status: Completed, Type: Enhancement

#157 Deploy
  src/main/java/com/example/gotogether/cart/repository/CartRepository.java
  src/main/java/com/example/gotogether/reservation/controller/ReservationController.java
  src/main/java/com/example/gotogether/reservation/service/impl/ReservationServiceImpl.java
Labels: For: CI/CD

#158 Feat banner
  src/main/java/com/example/gotogether/page/dto/BannerDTO.java
  src/main/java/com/example/gotogether/page/entity/Banner.java
Labels: For: Backend, For: CI/CD, For: Frontend

#159 Deploy
  src/main/java/com/example/gotogether/page/dto/BannerDTO.java
  src/main/java/com/example/gotogether/page/entity/Banner.java
Labels: For: CI/CD

#160 Refactor: Board 테이블 권한 컬럼 추가 및 관련 코드 리팩토링
  src/main/java/com/example/gotogether/board/dto/BoardDTO.java
  src/main/java/com/example/gotogether/board/entity/Board.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
Labels: For: API, For: Backend, Priority: High, Status: Completed, Type: Enhancement

#161 Deploy
  src/main/java/com/example/gotogether/board/dto/BoardDTO.java
  src/main/java/com/example/gotogether/board/entity/Board.java
  src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
Labels: For: CI/CD

#162 feat: 상품수정시, group이 없는 경우에도 작동되도록 수정
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
Labels: For: CI/CD

#163 Deploy
  src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
Labels: For: CI/CD
